include: package:lints/recommended.yaml

analyzer: 
  exclude:
    - lib/prisma/prisma_generated.dart
    - lib/prisma/prisma_generated.g.dart

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true


linter:
  rules:
    await_only_futures: true
    always_use_package_imports: true
    
    only_throw_errors: true
    directives_ordering: true
    use_enums: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    unnecessary_parenthesis: true
    unnecessary_null_checks: true
    prefer_final_locals: true
    prefer_final_parameters: false
    unnecessary_const: true
    unnecessary_brace_in_string_interps: true
    unawaited_futures: true
    type_init_formals: true
    type_annotate_public_apis: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_final_in_for_each: true
    prefer_const_declarations: true
    parameter_assignments: true
    cast_nullable_to_non_nullable: true
    avoid_void_async: true
    avoid_slow_async_io: true
    avoid_print: true