name: dart_backend
description: An new Dart Backend template
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_annotation: ^4.6.0
  orm: 
    path: /home/aliammar/Desktop/prisma/orm
  shelf_plus: ^1.4.0
  injectable:  
  get_it:  
  


dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  injectable_generator:  
  shelf_router_generator:
